FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 5173

# Флаг --host обязателен, чтобы Vite принимал соединения извне контейнера
CMD ["npm", "run", "dev", "--", "--host"]